title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jiinyy.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Jihyun'
  last_name: 'Bang'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username: jiinyy
  email: 
  vk_id: 
  telegram_name: 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


